resources:
- name: golang-app
  type: git
  source:
    uri: git@github.com:JizongL/fullstack-golang-project.git
    branch: master
    private_key: ((deploy_key))
- name: go-image
  type: docker-image
  source:
    repository: golang
    tag: "alpine3.12"

- name: s3
  type: s3
  source:
    bucket: foo
    versioned_file: my_build
    access_key_id: ((my_access_key))
    secret_access_key: ((secret_key))

jobs:
- name: test
  plan:
  - get: golang-app
  - get: go-image
  - task: run-tests
    image: go-image
    config:
      platform: linux
      inputs:
      - name: golang-app
      run:
        path: /bin/sh
        args:
          - -xc
          - |
            cd golang-app
            go test -v ./...
- name: build
  plan:
  - get: golang-app
    passed:
    - test
  - get: go-image
  - task: build-go-app
    image: go-image
    config:
      platform: linux
      inputs:
      - name: golang-app
      outputs:
      - name: built-app
      run:
        path: /bin/sh
        args:
          - -xc
          - |
            cd golang-app
            go build .
            mv ./web built-app/
  - put: s3
    params:
      file: built-app/web

# - name: deploy
#   plan:
#   - get: golang-app
#   - task: deploy