
resources:
- name: golang-app
  type: git
  icon: github
  source:
    uri: git@github.com:JizongL/fullstack-golang-project.git
    branch: master
    private_key: ((deploy_key))
- name: go-image
  type: docker-image
  source:
    repository: golang
    tag: "1.15.5-buster"

# - name: s3
#   type: s3
#   source:
#     bucket: foo
#     versioned_file: my_build
#     access_key_id: ((my_access_key))
#     secret_access_key: ((secret_key))

jobs:
- name: test
  plan:
  - get: golang-app
  - get: go-image
    trigger: true
  - task: run-tests
    image: go-image
    config:
      platform: linux
      inputs:
      - name: golang-app            
      run:
        path: /bin/sh
        args:
          - -xc
          - |
            apt-get update
            apt-get install mariadb-server -y
            service mysql start                                    
            cd golang-app            
            mysql < pkg/models/mysql/testdata/inittestdb.sql
            go test -v ./...
            go build ./cmd/web
            service mysql stop
      outputs:
      - name: golang-app          
  - task: build   
    config:
      platform: linux                  
      image_resource:
        type: docker-image
        source: {repository: ubuntu }          
      input:
        - name: golang-app
      run:
        path: /bin/sh
        args:
          - -xc
          - |
            ls -a